### ISSUE TITLE
Give users an indication that annotations are updating and done updating

### ISSUE THREAD

**Issue by lightandluck** [edgi-govdata-archiving/web-monitoring-ui#107]
We want go give users feedback when they apply annotations that it is happening and has finished. We haven't spent much time on visual design, so I'm proposing just changing text in the meantime.

1. The user clicks on `Update Record`, the text changes to `Updating...` while the request is being made. We can add `.dotdotdot` class to animate ellipses.
2. When the request finishes the text changes to `Updated`. 
3. When the user changes any annotation or notes, the text changes back to `Update Record`.
4. If the user navigates away from the page, either back to list or through pagination controls, the text also resets back to `Update Record`. We don't have to maintain this state.

**Comment by Mr0grog** [comment]
Seems like a good start to me. 👍 

Adding to the dictionary/important changes list should also trigger this behavior (since they are, under the hood, also basically just posting an annotation). Basically, whatever piece of state is tracking that an annotation is still being posted should probably be triggered by and affect the “update record,” “add important change,” and “add to dictionary” buttons together.

**Comment by lightandluck** [comment]
Agreed ^^^ Copy everything I said for those actions as well.

**Comment by lazywithclass** [comment]
Whenever I click on "update record" I get

> Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. Origin 'http://dagobah:3001' is therefore not allowed access.

Where `dagobah` is my hostname. I believe we could have the dev environment allow all origins for CORS, if you point me in the right direction I can have a look.

**Comment by Mr0grog** [comment]
Augh! Looks like I broke authentication on the staging server when I upgraded dependencies on Friday. Thankfully that hadn’t been deployed to production yet! It should be fixed now. More info here: https://github.com/edgi-govdata-archiving/web-monitoring-db/pull/126

**Comment by lazywithclass** [comment]
@lightandluck I think it would be easier to have a loading icon somewhere, rather than changing the text, the reason is that whenever you want to update it to the agreed one we can just change it in the component rather than everywhere we changed the text.
Also, it would be much easier to me since I'm nowhere near a React expert / fan :D

**Comment by lightandluck** [comment]
Sure, if it makes it easier for you. One thing you can try is to show the `<Loading />` component instead of the `<AnnotationForm />` while the app is updating. Or if you have something else in mind, go ahead and try it. 

I'm new to React as well, so not sure what the best approach would be. Whatever you decide, can you add a short write-up describing design choices and reasoning here? It'll help when reviewing the subsequent PR.

**Comment by lazywithclass** [comment]
Sure I will!

**Comment by lightandluck** [comment]
Fixed in #111 and merged in [42598f9](https://github.com/edgi-govdata-archiving/web-monitoring-ui/commit/42598f93533ab0169e2044832f52eb7ab77f9f33)
