### ISSUE TITLE
Add state management with Redux

### ISSUE THREAD

**Issue by lightandluck** [edgi-govdata-archiving/web-monitoring-ui#126]
When the project was first migrated to React it was [small enough that we put off adding Redux](https://github.com/edgi-govdata-archiving/web-monitoring-ui/pull/48#issuecomment-303783316) but now [issues are cropping up](https://github.com/edgi-govdata-archiving/web-monitoring-ui/pull/117#discussion_r140591993) where it seems like we should re-visit this. I have no personal preference, but looks like we were planning on using Redux already, so should plan to implement it in a future milestone.

**Comment by SYU15** [comment]
Reopening this as I feel like this topic needs to come back from the dead. Clientside state will become increasingly complex with the addition of more advanced search and re-adding annotations. I was considering adding the dependency possibly before date range search is implemented, but open to other ideas. Let me know if you have any concerns.

**Comment by thecalliopecrashed** [comment]
Dibs!

**Comment by SYU15** [comment]
Thanks for offering @thecalliopecrashed. It'd be great to get this done though I am a bit concerned this will be a bit of a beast to tackle starting off since in my mind it would include refactoring at least part of how we load pages into the application as a proof of concept (maybe @Mr0grog has other thoughts though). We could perhaps split up this issue into discrete parts to make it more manageable? We also have some other issues that are more self-contained. Lmk if you have a preference @thecalliopecrashed!
