### ISSUE TITLE
fix db link to monitoring.envirodatagov.org

### ISSUE THREAD

**Issue by weatherpattern** [edgi-govdata-archiving/web-monitoring-ui#162]
Step To Reproduce:
1. Log into API (https://api-staging.monitoring.envirodatagov.org/)
2. Click on "EDGI Web-Monitoring Database" link on the upper left-hand corner

Result:
Link points to https://api-staging.monitoring.envirodatagov.org

Expected Result:
Link points to monitoring.envirodatagov.org

**Comment by lightandluck** [comment]
@weatherpattern I don't think the link was made to point to the UI. It's basically like a "Home" link that goes back to the main page. It's confusing because "Api" and "Database" are synonymous (which wasn't a conscious choice, just how things have evolved over time.)

That said, if that's the expected behavior @Mr0grog would have to change it. I don't have access to deploy the -db project. (And shouldn't! Because I would have no idea what I was doing.) Also, if changing, if we're looking at the staging -db it should link to monitoring-staging...gov and production -db should link to monitoring...gov.

**Comment by weatherpattern** [comment]
Ah. I don't know where I got that, I thought that is how it worked before. Will discuss and close if not necessary.

And yes, api-staging would point to the staging, and api-prod to prod.

**Comment by Mr0grog** [comment]
Yeah, @lightandluck is dead on with this; it’s as intended. The DB is not supposed to really know anything about the UI—as far as the code there cares, there’s nothing in the universe it should know about other than itself and the diff server.

Part of the idea here was that the UI project is not really a canonical interface this this database; many people/orgs/teams could write interfaces that best suit their process or goals (e.g. a viewer for the public with lots of explanatory text vs. a minimal, focused tool for analysts to quickly move through and annotate changes vs. a debug/admin/review-focused tool that lets you browse and manipulate annotations and users, etc. There were sort of two main goals of that:

- Giving us ways to not eventually turn UI into some huge, complicated, does-everything tool
- Giving us a way to share the use of the platform while allowing different teams or users to have an interface that best supports their process without getting in the way of each other. (They could also re-deploy the whole stack themselves since it’s open source, but a lot of folks have really wanted us to be able to share the running platform, which could drastically reduce cost and effort for others.)

**Comment by weatherpattern** [comment]
Got it. Thanks for the explanations. Closing the issue.
