### ISSUE TITLE
Get versions on details page from` page/{page_id}/versions` api endpoint

### ISSUE THREAD

**Issue by lightandluck** [edgi-govdata-archiving/web-monitoring-ui#215]
The details page currently grabs versions to populate the dropdowns using a version object that is attached to the page object. This version object will soon go away as explained in [this issue in -db](https://github.com/edgi-govdata-archiving/web-monitoring-db/issues/264). We'll need to grab versions instead from `page/{page_id}/versions` endpoint.

**Comment by lightandluck** [comment]
Also, we agreed that an acceptable cutoff point to limit number of versions returned, for now, is November 1, 2016. Is that right? @Mr0grog @weatherpattern

**Comment by lightandluck** [comment]
Thanks for the guidance! I'll keep those points in mind. I'll be working on this later tonight and tomorrow.

**Comment by lightandluck** [comment]
Hi @Mr0grog @weatherpattern @gblike,
So as I worked on this more, I became unsure what's the best approach now, so coded up some options. 

[First option](https://github.com/edgi-govdata-archiving/web-monitoring-ui/tree/215-too-many-versions-kick-the-can-down-the-road), is to hard-code the cut-off date to Nov. 1, 2016. We would have to tell analysts this is happening. This is a short-term solution but acceptable, because with Versionista they are limited already by versions from Jan. 17, 2017 onward. 

I'm not sure what to do with `^` shortcut. I think with all the IA imports, this becomes meaningless. We are using this as a shortcut to get to the earliest version or `base` which for analysts means Jan 17, 2017. But going forward the earliest version could be from any time. Don't think it's worth working around this hack, unless we [resolve this issue](https://github.com/edgi-govdata-archiving/web-monitoring-ui/issues/173) with analyst input.

[Second option](https://github.com/edgi-govdata-archiving/web-monitoring-ui/tree/215-alternate-approach-date-filter), we have the cutoff, but analysts are able to adjust this to an earlier date. I created an input where they could select the earliest date and we filter from there. It defaults to Nov. 1 2016. ![screen shot 2018-04-10 at 5 28 30 pm](https://user-images.githubusercontent.com/3014813/38590207-a2fa0b6a-3ce4-11e8-94d8-9f2ce2b44b3d.png)
I decided to store their choice in `sessionStorage`. Right now, I only added the ability to change the `from date` cutoff, but it's trivial to add a cutoff for `to date`.

Again, this also makes the `^` shortcuts not useful. Right now, the only place I know that this shortcut is being used is in the annotation export which is hidden. Just flagging that would need to change, depending on what we decide.

[The last option](https://github.com/edgi-govdata-archiving/web-monitoring-ui/tree/experimental-fancypants-timeline-a-new-age), which I would prefer, is reviving Rob's timeline. I created a branch with those additions on top of latest `master`. If we want to go this route we should import all versions for IA. Rob had a lot of good points and I'm starting to agree with them especially
> there is also a really big data benefit in having a record of every capture/snapshot/observation/sample: analysts regularly head over to the Internet Archive to try and get a better sense of when a change may have actually occurred

I think the timeline would work perfectly to help visualize this.

I talked briefly to Ray about this and he suggested we could do this in steps? Sorry, my brain is mush and I'm probably not explaining myself well. I hope we can talk this through at next dev meeting.

**Comment by Mr0grog** [comment]
Sorry for not commenting earlier. Getting some of my thoughts from the meeting in writing and expanding on them a bit here…

> First option, is to hard-code the cut-off date to Nov. 1, 2016. We would have to tell analysts this is happening.

I think this is a good place to start.

> I'm not sure what to do with ^ shortcut.

I think we should leave this as-is, so that it continues to resolve against the cutoff date above (rather than earliest *actual* version. I think that will feel more consistent for a user.

> Don't think it's worth working around this hack, unless we resolve this issue with analyst input.

Agree.

> Second option, we have the cutoff, but analysts are able to adjust this to an earlier date. I created an input where they could select the earliest date and we filter from there. It defaults to Nov. 1 2016.

This seems like a great step 2. However, I think this is the right time to introduce a settings panel. Not having one has helped me not add needless controls (I’ve thought about lots of things!), but maybe it’s finally time for it. This could be the first option in it. I think that’s better than yet another control people probably won’t fiddle with very often taking up space at the top of the screen.

(Actually, I think step 1 shouldn’t quite be hard-coded: it should have the same settings infrastructure as this, just without the UI. The UI work is step 2.)

> I decided to store their choice in `sessionStorage`.

I feel like someone might want this to stick around longer than their browser window. Pretty sure I’ve mentioned this idea before, but I’m thinking a kind of “layered local storage” might make sense here:

```js
// Example only; production code needs try/catches and other fanciness
LayeredLocalStorage = {
  set (key, value) {
    if (window.sessionStorage) {
      sessionStorage.setItem(key, value);
    }
    if (window.localStorage) {
      localStorage.setItem(key, value);
    }
  },
  get (key) {
    if (window.sessionStorage) {
      const value = sessionStorage.getItem(key);
      if (value != null) return value;
    }
    if (window.localStorage) {
      return localStorage.getItem(key);
    }
  }
}
```

That way, new windows inherit the latest value set from any window with the given key. This also gives us a nice place to put automatic serialization/parsing stuff, so we can save things like objects, arrays, and dates.

> I only added the ability to change the `from` date cutoff, but it's trivial to add a cutoff for `to` date.

Given the nature of the issue, I’m not sure we really want to add a `to` cutoff.

> The last option, which I would prefer, is reviving Rob's timeline.

🎉  we (I?) do need to get back around to cleaning that up and making it production-ready. This is definitely a good step 3, after we get the cutoff stuff done — after all, we might still want some of that infrastructure around — we don’t necessarily want to load a mind-bogglingly large list of versions into memory, for example, and we might still want the way it affects `^` for a while.

**Comment by lightandluck** [comment]
Thanks for all the input. I agree with everything and have been working that way! PR's coming soon.
