### ISSUE TITLE
co-ordinate UI work

### ISSUE THREAD

**Issue by titaniumbones** [edgi-govdata-archiving/web-monitoring-ui#25]
We have a number of people working on UI-related code (@agillette, @allanpichardo, @lightandluck). We also have some designers, and some users (@ambergman, @trinberg, @mayaad). Work on this module should proceed in a co-ordinated way with input from all of hte above as appropriate!

**Comment by lightandluck** [comment]
Sounds good, thanks Matt! I'd like to introduce myself because I haven't met anyone else on this thread. My name is Kevin. I'm a front end dev recently moved to the Bay Area, originally from San Diego. I like designing interfaces that make people's lives easier. I was at the SF Bay Data Rescue event 2 weeks ago and am volunteering to help design and code the UI. Thanks and nice to meet everyone!

**Comment by trinberg** [comment]
Per @danielballan's suggestion - I wanted to share a tutorial video, led by @mayaad, that explains the website tracking team's current workflow: https://www.dropbox.com/s/ciixvu612ktf4nt/new_tracking_training.mp4?dl=0

It's 50 minutes and details how the team of analysts is going to screen through changes that Versionista flags and how they will classify each page diff as having significant/insignificant content on it. At the moment we're working with csvs/google sheets and Versionista's diff UI. 

@ambergman is the point of content on answering any questions you may about the current workflow and how we imagine it will change have so feel free to bug him!

**Comment by danielballan** [comment]
@lightandluck It's great to have you working on this! FYI, I am basing my work in #28 on your `ui_mockup` branch. As I wrote over there, I'm leaning toward a Python backend as opposed to node because I think it will easier for data science-y types to contribute, but I'm hoping to leave the UI stuff as is. As an example, JupyterHub is architected similarly (Python server + TypeScript front-end).

@trinberg Thanks! This will be really useful.

**Comment by lightandluck** [comment]
@trinberg This is just what we needed, thanks! I'll put up the mockup online somewhere later tonight, so the analyst team can see it. I'll also write up what my understanding of the process was and motivations for what's in the UI. We can discuss what lines up with the actual process and figure out what can be carried over to the next iteration and how to improve.

@danielballan Glad to be of help! I read over the thread. My only question is, who do we expect to continue working on this website in the future? Web developers, data scientists, our just us? I'm not sure how complex this app will get or what type of data processing it will be doing on the backend. But, as an average web dev, I don't have any familiarity with Tornado. So if I was coming in new, I wouldn't have been able to contribute as much.

I liked the build system that @allanpichardo had setup. I was familiar with most of it, so it wasn't hard to see what he was doing and how to build on top of it. But, if we're going to do some intensive data processing or it's going to be mostly you working on the backend, go with Python.

I hope I don't have to do any backend work! (not my strength) so it really doesn't matter to me. As long as the frontend gets JSON data we agree on, I'm happy. We can discuss further on the issue thread.

Also, let's move to the dev-webdiff-ui slack channel for future communication. See everyone there!

**Comment by dcwalk** [comment]
@ambergman ^^ RE: next steps for UI
