### ISSUE TITLE
Review mockups from Web Monitoring Analysts

### ISSUE THREAD

**Issue by dcwalk** [edgi-govdata-archiving/web-monitoring-ui#35]
@ambergman has been working on exploring mockups with the website monitoring analysts, once those are provided there will need to be some review to see how they fit with prototyped UI.

(pulling this issue in from https://github.com/edgi-govdata-archiving/overview/issues/65)

**Comment by dcwalk** [comment]
@ambergman could you update on this?

**Comment by ambergman** [comment]
I apologize to everyone for the enormous delay in posting [these preliminary mockups of the Website Monitoring App](https://docs.google.com/presentation/d/1P9kPr-wPwoKbuhW3DHRfr_OeHyh9k1Avv_1vOH5U-Hg/edit#slide=id.p). These are based on my work on the website monitoring team and my first thoughts for a UI that could feasibly be built in the coming months, would mesh with the larger DB and processing efforts, and would retain much of the website monitoring team's current workflow, while making important improvements on the spreadsheet/Versionista interface currently being used. 

These mockups incorporate feedback from a number of the website monitoring analysts. But they will certainly be modified and added to after further discussion with analysts who have not yet been able to review them and in consultation with @danielballan, @lightandluck and other members of the Web Monitoring Dev team. 

Dan and Kevin: It would be great to get your feedback on both the mockups themselves and the way I've posted them here - let me know if you have a better thought than Google Slides. Also, the images aren't coming out great and a bunch of the text is hard to read, so I'll transcribe the feature descriptions later today, if you think that's useful.

Some notes: So far, only the "User" side of the app has been mocked up - the "Admin" views will be mocked up after further discussion in the coming days. The main admin features are, however, already listed: domain allocation, tracking trends, and tracking the progress of report writing. Because each of these can continue to be managed in spreadsheets outside of the app, a working user-side app would essentially amount to a viable product on its own - so it seems like a reasonable place to start.

**Comment by dcwalk** [comment]
@ambergman -- are you able to upload a higher quality version of the photos (outside of a presentation) to somewhere? 

My eyes are a bit terrible... but I'm unable to read the annotation text in most pages

**Comment by danielballan** [comment]
Yeah, I think transcribing the feature descriptions as you suggested would be useful.

**Comment by lightandluck** [comment]
I'm also having a hard time reading it. Maybe re-scan at higher resolution and bump up the contrast a bit so the writing isn't as washed out? The way its presented works for me

**Comment by ambergman** [comment]
I'm really sorry for the huge delay getting better images of the mockups out @dcwalk, @danielballan, @lightandluck, and everyone else. I really appreciate your patience. I was preparing some stuff for my trip down to Washington and then I was at an event here all day. As punishment for being so slow, I had the pleasure of going out to find a scanner (since my phone really wasn't getting decent res images). Anyway, I think the mockups (found in the [same presentation linked above](https://docs.google.com/presentation/d/1P9kPr-wPwoKbuhW3DHRfr_OeHyh9k1Avv_1vOH5U-Hg/edit#slide=id.g1b3b3a142b_0_20)) are readable now, if you either go into "presentation mode" or just zoom in, but things might still be less than ideal on other monitors. So, just in case, as Dawn suggested, I uploaded all of the images into [this Dropbox folder](https://www.dropbox.com/home/EDGI%20Website%20Monitoring%20App%20Mockups). If I have some free time tonight or tomorrow, I'll also try to go through and transcribe the feature notes. Let me know what you all think.

**Comment by danielballan** [comment]
@ambergman These are really beautifully done. Thanks for taking the time to pull together feedback.

**Comment by danielballan** [comment]
A list of the views mocked up in the Dropbox, for easy reference:
* User Dashboard View
* List View
* Diff View
* Identical Diffs View
* Page History View

**Comment by lightandluck** [comment]
[Presentation with annotations](https://docs.google.com/presentation/d/1zX2FtpRusbvUFESZgsaH4lkmNz7Yz8_T-65xS0tIuBU/edit#slide=id.g1b3b3a142b_0_20)

**Comment by lightandluck** [comment]
Next step is to sit down with analysts to observe process and figure what to implement in UI. Waiting on clarification of who the right point person to coordinate this with (most likely @mayaad).

**Comment by lightandluck** [comment]
Would be good to use as a starting point whenever we get analysts annotating in Scanner, but wouldn't be surprised if we scrapped everything
