### ISSUE TITLE
README link to tutorial for Google service account out of date

### ISSUE THREAD

**Issue by SYU15** [edgi-govdata-archiving/web-monitoring-ui#373]
[This tutorial](http://isd-soft.com/tech_blog/accessing-google-apis-using-service-account-node-js/) is from 2017 and no longer accurately reflects the flow for generating a service account key. As far as I can tell, you can't specify `Compute Engine default service account` anymore, you actually have to explicitly define the name and role before you can generate the credentials.

I was thinking of finding a more up-to-date tutorial that just shows how to create a service account key with project owner (full access to all resources) as the role, but wasn't sure if that was too permissive/problematic for whatever reason.

**Comment by Mr0grog** [comment]
I think that’s fine, but maybe we should include a note not to ever use a setup like that in production! :)

**Comment by Mr0grog** [comment]
Reclassifying this as a bug, since it is actually incorrect documentation that is hard to get set up correctly without. Since all the Google sheets-related functionality is turned off right now, the right answer may also be to just pull this out or at least make it clear that you don’t need to set up a service key.

**Comment by SYU15** [comment]
Hmm...maybe remove it for now and then rewrite it when it is turned back on? I can make a PR for it if so.

**Comment by Mr0grog** [comment]
👍 Sounds fine to me.
