### ISSUE TITLE
Migrate CSS for page-list component

### ISSUE THREAD

**Issue by SYU15** [edgi-govdata-archiving/web-monitoring-ui#407]
Right now the CSS for this component lives in `styles.css`:
https://github.com/edgi-govdata-archiving/web-monitoring-ui/blob/master/src/css/styles.css#L130

This is vanilla CSS that is currently loaded at the global level but we are currently migrating our CSS to [CSS Modules](https://github.com/css-modules/css-modules).

Here is an [example PR](https://github.com/edgi-govdata-archiving/web-monitoring-ui/pull/393) where the `source-info` component was migrated over.

To accomplish this we need to do the following:

1. Add the CSS to the new pipeline by migrating it out of `styles.css` and into a new file called `page-list.css`. The directory structure should look like this:
```
src/components
└─┬ page-list
  ├── page-list.jsx
  └── page-list.css
```

2. In `page-list.jsx`, the new CSS file needs to imported:
```
import './page-list.css';
```

3. The `.page-list tbody tr` and any other selectors using more than one element/class name/etc., need to be refactored to be a single class name. Something like `.page-list-row`, for example, could work or something similar. These classes need to be added/replaced in the `page-list.jsx` file. Feel free to ask if you aren't sure where the new classes should go in the markup.

4. In `page-list.jsx`, the `className` tags needs to be added or replaced for `styleName` **for the component level styles only**. Global styles should stay in `className` tags and a component can have both `className` and `styleName` tags at the same time if necessary. Feel free to ask if you aren't sure if a style falls under either category. (This basically determines which classes get suffixed with a hash to make sure it is scoped at the component level).

5. Fix any tests that fail because you refactored the class names. You can run the tests using `npm test`.

Here is an example of `styleName` vs `className` being used in our codebase:
https://github.com/edgi-govdata-archiving/web-monitoring-ui/blob/06faddae40f19eb7785e87ffc2d33055500f2658/src/components/source-info/source-info.jsx#L65-L73

**Comment by jatinAroraGit** [comment]
Hi there,
I would like to work on this issue.
Can it be assigned to me please.
Thanks.

**Comment by Mr0grog** [comment]
That’s great! Would you please work through and complete #411 first, though?

**Comment by jatinAroraGit** [comment]
Sure @Mr0grog , on it.

**Comment by jatinAroraGit** [comment]
Hey @Mr0grog ,
So I am finished with fixing this issue but cannot seem to pre commit it due to an error with patterns not matching.
The files waiting for commit are CSS and JSX files.
I get this error : 
`> eslint --ignore-path .gitignore './**/*.{js,jsx}'


Oops! Something went wrong! :(

ESLint: 6.3.0.

No files matching the pattern "'./**/*.{js,jsx}'" were found.
Please check for typing mistakes in the pattern.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! web-monitoring-ui@0.1.0 lint: `eslint --ignore-path .gitignore './**/*.{js,jsx}'`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the web-monitoring-ui@0.1.0 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jaaro\AppData\Roaming\npm-cache\_logs\2019-10-01T03_46_08_840Z-debug.log`

Thanks.

**Comment by jatinAroraGit** [comment]
Hey @Mr0grog , did a commit addressing the requested changes. Let me know if there are any issues.
Have a good day.
