### ISSUE TITLE
Save search state when transitioning between /pages and /page/:id

### ISSUE THREAD

**Issue by SYU15** [edgi-govdata-archiving/web-monitoring-ui#438]
Right now if you:

1. Make a search query on the main `/pages` route
2. Then click on a particular page entry (`/page/:id`) 
3. Return to `/pages`

the list of pages still maintains the state of the last search query. This is confusing because the search bar's state resets so it is unclear to the user that the list of pages is also not reset.

We should persist whatever state is set in each of the search fields so it still renders when the user comes back to `/pages`.

<img width="1439" alt="Screen Shot 2019-11-23 at 11 48 57 AM" src="https://user-images.githubusercontent.com/10149117/69488739-5078ea80-0e22-11ea-8b1c-223c4a512d5f.png">

**Comment by Mr0grog** [comment]
I think it actually might make more sense to make sure the right search query data stays in the search bar, rather than reset the current search. After all, the current search results are what guide the next/previous buttons in the page details view — the current search was meant to be “sticky” so you could easily flip back and forth between views. (No disagreement that the current state of affairs is super confusing!)

**Comment by SYU15** [comment]
I see, ok will change the nature of the issue now that I understand the original intent.
