### ISSUE TITLE
TODOs v0

### ISSUE THREAD

**Issue by danielballan** [edgi-govdata-archiving/web-monitoring-ui#49]
Notes from @Mr0grog's comments on a call on what we need to do on the UI side for 'v0'

- Error handling
- Authentication
- Improving API between ui and db
- Who is assigned which URLs over which timeframes -- maybe use a Google Spreadsheet to manage this rather than building a separate UI for it

Later we can break this up into separate issues if that helps.

**Comment by lightandluck** [comment]
Was there something specific for improving the API that should be done one the UI side? I don't think I caught what was said about that during the meeting. If not, we can close this because separate issues for everything else have been opened.

**Comment by Mr0grog** [comment]
> Was there something specific for improving the API that should be done one the UI side?

I was mostly thinking: better building out the [`services/web-monitoring-db`](https://github.com/edgi-govdata-archiving/web-monitoring-ui/pull/48/files#diff-4df3c64872ce4d576d96db40ae40fbb5) module. I’m only shooting to get the least it needs for the *currently existing* UI in #48, so it will almost certainly need some love in terms of querying, paging, interacting with changes, etc.

I thought it might be possible to break out as a separate piece because you could probably treat it as a fairly independent module and write it in a way that other potential UIs could make use of.

**Comment by lightandluck** [comment]
Closing because tasks have separated into issues
