### ISSUE TITLE
Setup CSS pre- or post- processor

### ISSUE THREAD

**Issue by lightandluck** [edgi-govdata-archiving/web-monitoring-ui#54]
Currently the project uses raw css files that are copied over to the dist folder directly when building. It would be helpful to use Sass or PostCSS for those files instead. I've only used Sass myself, but open to any suggestions.

Archivers 2.0 looks like they're using Sass, so in the interest of having a tech stack that coincides to increase transference of code and knowledge, I'd vote for Sass. 

@b5 @Mr0grog @danielballan @patcon

**Comment by titaniumbones** [comment]
I'm not really relevant but I like the idea of standardizing our stack
across projects as much as possible. Also PostCSS looks lharder.

Kevin Nguyen <notifications@github.com> writes:

> Currently the project uses raw css files that are copied over to the dist folder directly when building. It would be helpful to use Sass or PostCSS for those files instead. I've only used Sass myself, but open to any suggestions.
>
> Archivers 2.0 looks like they're using Sass, so in the interest of having a tech stack that coincides to increase transference of code and knowledge, I'd vote for Sass. 
>
> @b5 @Mr0grog @danielballan @patcon 


--

**Comment by b5** [comment]
Love to see sass make it's way into the project, but if we can find a convincing reason to use a different css preprocessor, I'd be happy to port archivers preprocessor over to maintain parity. The more community-oritiented answer is use sass, due to the widespread popularity of bootstrap, earlier versions of rails, and related projects. All of these drive _many_ people to learn sass.

**Comment by Mr0grog** [comment]
I seem to keep winding up in the situation where I have both SASS and PostCSS both in use (most commonly: adding PostCSS for autoprefixing), so I have some interest in seeing if just PostCSS is feasible in order to slim down the stack. I am also curious if one of the many PostCSS import/include modules (5 by my count 🙁) solve the I-imported-this-file-twice-but-it-should-only-happen-once problem so you can properly do dependencies (you can do it with SASS, but only by writing extra JS glue code).

That said, PostCSS is definitely way more complicated. You can pretty much re-create SCSS through a variety of plug-ins, but you have to find them all and cobble them together (though there are some high-level ones that wrap-up a bunch of other modules like http://cssnext.io). There are multiple tools for doing the same thing, too, so there is a lot more overhead in choosing things.

**Comment by Mr0grog** [comment]
Anyway, I guess:

- If someone has time and wants to fiddle with stuff, I’d love to look into doing just PostCSS
- Otherwise, let’s just do SCSS and keep it simple. We’ll add onto that or change things if needed later.

**Comment by patcon** [comment]
Would this be a good issue to tag as `first-timer`?

**Comment by Mr0grog** [comment]
Generally I'd say no, since this is about making a deep, wholesale change to the way the app is built and put together. That said, the code base is *miniscule* right now, so this kind of change is relatively manageable at the moment.

If you are searching for things to tag, #58 might be a good candidate.

**Comment by Mr0grog** [comment]
I think some flavor of this is still important.

**Comment by SYU15** [comment]
Whoops, forgot to add a closing keyword to my PR, so manually closing this.
