### ISSUE TITLE
Add keyboard navigation to UI

### ISSUE THREAD

**Issue by titaniumbones** [edgi-govdata-archiving/web-monitoring-ui#58]
It would be nice ot have at least next/previous navigation available by keyboard as well as mouse. Some other shortcuts might also be helpful, e.g., toggling back and forth between dashboard view and individual page view.

**Comment by Mr0grog** [comment]
> toggling back and forth between dashboard view and individual page view

You can actually already go back to the dashboard from a page with the `esc` key. It’s a little ambiguous going the other direction, but we could probably use the last page you viewed.

You can also use the browser back/forward buttons or `cmd+←`/`cmd+→` (mac) or `ctrl+←`/`ctrl+→` (windows) to go back and forth (browser history should work fine in the new React app).

**Comment by Mr0grog** [comment]
Since there is already some keyboard support, this would be a great issue for someone working on the Mozilla Global sprint to hop in and help on :)

See the existing keyboard support in [`page-details.tsx`](https://github.com/edgi-govdata-archiving/web-monitoring-ui/blob/master/src/components/page-details.tsx#L39-L58) for inspiration or show a better technique for keyboard shortcuts in React.js if you have one!

**Comment by lightandluck** [comment]
Still would be great to have, but looks far off
