### ISSUE TITLE
Allow quick copying of annotations to another row

### ISSUE THREAD

**Issue by titaniumbones** [edgi-govdata-archiving/web-monitoring-ui#63]
- analysts often want to copy annotations from one row to another.  We need some UI to allow this.
- sometimes similar types of changes are applied to a page repeatedly. It would be nice to have some way to indicate that a diff is similar to one we've seen before. 

(@lightandluck I'm not quite sure I've translated your notes right, pls feel free to edit!)

**Comment by lightandluck** [comment]
Not sure how relevant this will be because we haven't worked on the UI for so long but not much has changed in the mechanical process for analysts, so I'd keep this open because it was an important feature that was wanted.

**Comment by Mr0grog** [comment]
I’m going to go ahead and close this as no longer especially relevant.

- Today, analysts have several tools in their spreadsheets that do a decent job of indicating changes that appear to be the same. We also make sure to group all those rows together instead of spreading them all over.

- We don’t have annotations in the app anymore. If we add that back, thinking about this issue might be useful again.
