### ISSUE TITLE
Add navigation/routes for “all pages” and “my pages”

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring-ui#96]
Add routes and navigation to move between displaying a list of all tracked pages and only the pages the currently logged in user is assigned to monitor. See also: https://github.com/edgi-govdata-archiving/web-monitoring-ui/pull/79#issuecomment-314989435

**Comment by lightandluck** [comment]
1. Create “My Pages” and “All Pages” routes.  The root route would display/redirect to “my domains” if logged in and ”all” if not.
2. Create two additional links in the header. `My Pages` and `All Pages` that correspond to the new routes. They will be new list items in `ul.nav`
3. A logged out user will not see these links, because they will only see all pages by default.
